### ISSUE TITLE
Do notation with block doesn't yield methods

### ISSUE THREAD

**Issue by dmitryzuev** [dry-rb/dry-monads#129]
**Describe the bug**

After using `dry-transaction` I had a habit to call "commands" special way with passing a block to it and matching result, example:
```ruby
TransactionCommand.new.call(params) do |result|
  result.success { process_success }
  result.failure { process_failure }
end
```

When I tried to do the same with transaction, i encountered bug: `yield some_method` always returns `nil`.
I know that passing a block to do monad isn't a case, but it'll be nice to raise some error if it's not supported.

**To Reproduce**

```ruby
require 'dry/monads'
require 'dry/monads/do'

class ValidateAccount
  include Dry::Monads[:result]
  include Dry::Monads::Do.for(:call)

  def call(params)
    values = yield validate(params)
    Success(values)
  end

  def validate(params)
    Success(params)
  end
end

# always returns `nil`
ValidateAccount.new.call({ hello: 'world' }) do |result|
  result.success { |values| puts values }
  result.failure { |error| puts error }
end

# returns `Success({ hello: 'world' })`
ValidateAccount.new.call({ hello: 'world' }) do |result|
  result.success { |values| puts values }
end
```

**Expected behavior**
I'm not sure what behavior should be, but here are possible scenarios:
1. Raise error if block passed to `#call`
2. Support `dry-transaction`-like code: https://dry-rb.org/gems/dry-transaction/0.13/basic-usage/#calling-a-transaction

**Your environment**

- Affects my production application: **NO**
- Ruby version: 2.6.5
- OS: macOS 10.15.5

**Comment by flash-gordon** [comment]
I don't think I follow. How is the code you posted supposed to work? You only have dry-monads modules in the class.
Sidenote: blocks passed to a method discards do notation, it's intentional. It allows you to mix both styles in a class when you `include Dry::Monads[:do]` i.e. wrap all methods. We probably could raise an exception when do notation is added via `.for(...)` but it would be a breaking change for 1.0.

**Comment by dmitryzuev** [comment]
My code supposed to work if it is written with `dry-transaction` like here: https://dry-rb.org/gems/dry-transaction/0.13/basic-usage/#calling-a-transaction.

I know that monads are completely different from transaction, but I spent few hours trying to understand why my code didn't work 😁. If I'm only one confused with this, you can close this issue, no problem!

> blocks passed to a method discards do notation, it's intentional. It allows you to mix both styles in a class when you include Dry::Monads[:do] i.e. wrap all methods.

It's interesting. Maybe some examples in the docs would be great help!

Thanks

**Comment by flash-gordon** [comment]
The link you posted has another module included, namely `MyApp::Transaction`. Your `ValidateAccount` has only dry-monads modules. Presumably, you have something like `include Dry::Transaction(container: Container)` in your class you need to `include Dry::Monads::Do.for(:call)` _before_ that line. It is important because dry-transaction includes dry-matcher which, in order, intercepts the outer block hence should be added later.
I would suggest you switch to [pattern matching](https://dry-rb.org/gems/dry-monads/1.3/pattern-matching/) which doesn't have such quirks.

> It's interesting. Maybe some examples in the docs would be great help!

Feel free to send a patch.
