### ISSUE TITLE
can not use _url helper

### ISSUE THREAD

**Issue by mateuszbialowas** [dry-rb/dry-monads#168]
## Describe the bug

I have classes:
```
require 'dry/monads'
require 'dry/monads/do'

class BaseService
  include Dry::Monads[:result, :do]
end
```
```
class Create < BaseService
     include Rails.application.routes.url_helpers
     def call
        path = post_url
     end
end
```

When I call `post_url` then I have error: 
post_url StackError: stack level too deep
/Users/mateuszbialowas/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/dry-monads-1.5.0/lib/dry/monads/do.rb:128:in `default_url_options'

When I remove the inheritance from BaseService, then I can call post_url with no error. 

How can I use dry monads with do notation and call URL helpers?

## Expected behavior

I would like to call post_url with no error. I want to be returned full path: http://localhost:3000/posts

## My environment

- Affects my production application: NO
- Ruby version: 3.1.0
- OS: mac 13.3

**Comment by flash-gordon** [comment]
I don't know exactly what causes this but I have a clue. `do` notation adds an implicit block to methods once they are defined. This usually doesn't lead to problems but this case seems to be an exception (no pun intended). I would try including `Rails.application.routes.url_helpers` _before_ `Dry::Monads[:result, :do]`. I can't test it, though, because you provided no code for reproducing the problem and I don't have easy access to a rails project atm. 

I don't think it's a bug, could be a limitation of `do` notation. It actually surprises me how rare such limitations happen in real life, when I wrote the code I had expected them to happen way more often. In the future, please ask a question at our forum at https://discourse.dry-rb.org/, we keep github for bugs only and "pre-approved" feature requests, it's easier to maintain things this way, thanks. If you wish, you can post a sample project showing the problem there, I'll take a look then.

**Comment by solnic** [comment]
I'd recommend including route helpers in a standalone object and re-use it instead of mixing lots of methods into a base service.

**Comment by flash-gordon** [comment]
@solnic that's what I'd do too. It's just not clear what causes the error (my minor curiosity, not reaching the level where I want to set up a rails project myself :)

**Comment by mateuszbialowas** [comment]
I solved the problem by adding method to the service:
```
def routes_helper
     Rails.application.routes.url_helpers
end
```

And now I can call this URL helper by `routes_helper.post_url`
