### ISSUE TITLE
Reflect method aliases in "constructors"?

### ISSUE THREAD

**Issue by citizen428** [dry-rb/dry-monads#45]
Unlike #42 this not supposed to be a major change, but as noted there the `Either` monad does somewhat double as a `Result` monad. So given that `right?` and `left?` are already aliased to `success?` and `failure?`, would it be reasonable to also alias the "constructors" defined in the mixin?

Essentially just this:

```diff
index 083c4f0..f48b32e 100644
--- a/lib/dry/monads/either.rb
+++ b/lib/dry/monads/either.rb
@@ -210,2 +210,3 @@ module Dry
         end
+        alias Success Right

@@ -216,2 +217,3 @@ module Dry
         end
+        alias Failure Left
       end
```

For reference, Rust originally had both, but then went with [Result](https://doc.rust-lang.org/std/result/) for the standard library. Relevant [quote](https://news.ycombinator.com/item?id=8470835):

>[W]e actually used to have both Either and Result, until one day we went through and realized that no code in existence was using Either and decided to go all-in on Result instead.

On a side-note, I find it would make `dry-transaction` code much more readable to the average user™:

```ruby
def validate(input)
  if input[:email].nil?
    Failure(:not_valid)
  else
    Success(input)
  end
end
```

**Comment by timriley** [comment]
I think this is a great idea. It'd make teaching these gems more straightforward, especially since by our conventions so far, we're mostly using `Either` as a result object.

I'd be happy for both the `Right`/`Success` and `Left`/`Failure` type "constructors" to remain here in the long term, since this is a general purpose library after all, but it might be worth having a discussion about which of these name pairs becomes the "primary" name, or whether we can create full class aliases for each of these (i.e. it might be disconcerting for a user creating `Success("hi")` to see it become `Right("hi")` immediately afterwards).

**Comment by timriley** [comment]
@flash-gordon what do you think?

**Comment by flash-gordon** [comment]
@timriley @citizen428 yeah, this is a good suggestion, although you @timriley made an excellent point about unexpected naming confusion, I’d try to have full class aliases but this will require setting up a custom equalizer. Overall, having weird names from the “world of monads” scares people even the concepts are not that complex. I think, that’s one of the reasons Rust came up with “normal” names in the end and I guess we should make a similar move so I’ll give it a shot

**Comment by citizen428** [comment]
@flash-gordon I have no problem with monadic vocabulary, I just think that so far `Either` has mostly been used in the context of what Rust calls `Result` (so does [MonadEx](https://hexdocs.pm/monadex/Monad.Result.html) for Elixir btw) and making things accessible/less "scary" seems like a good move. 

I'll play around with over the weekend.

**Comment by flash-gordon** [comment]
OK, we renamed Either to Result in 0.4.0
