### ISSUE TITLE
Document how to use monads in specs/tests

### ISSUE THREAD

**Issue by deepj** [dry-rb/dry-monads#87]
Hello,
I think it would be nice-to-have some documentation how to use monads in specs/tests properly. It would help in adaptation as well :)

**Comment by flash-gordon** [comment]
@deepj what do you mean by that? What kind of special support in specs can be useful?

**Comment by deepj** [comment]
@flash-gordon I meant something like this https://dry-rb.org/gems/dry-view/testing/. What I mean to set preferable and recommendation how to tests monads in rspec/minitest.

**Comment by waiting-for-dev** [comment]
@deepj I think that there is no need of dedicated documentation, because there is no special ceremony needed to test monadic values. For example, you can set expectations for your wrapped values within `bind` blocks, or just call `.value!`, for result kind monads, to extract it when you know it wraps a success. Just use the regular API. If you need help with some special scenario maybe you can ask for help in dry-rb discussion forum.

**Comment by deepj** [comment]
@waiting-for-dev I don’t have a problem with that. I just reflect some issue one junior developer which would like to learn monads via Ruby.

She wasn’t sure what the proper way is.

Be more empatic for juniors.

**Comment by waiting-for-dev** [comment]
@deepj , I'm quite shocked with your message, because my intention was very far from being rude or not empatic. I was trying to give some help. I'm not a native English speaker, so maybe there is something in my message that sounds in a way I didn't mean it. If so, I'm really sorry.

The core message I wanted to communicate is that there is nothing special you should do to test values wrapped in monads, besides using the monads API. For this reason I don't think (just my opinion) there is documentation missing here. So, as I don't this is an issue in `dry-monads` project, I recommended you to ask for whatever you need in dry-rb discussion forums, as it is the place where you can find support. There, more people, including myself, would be more than welcome to guide you in whatever you need.

**Comment by deepj** [comment]
@deepj English is not my native language too. Again, I reflect an experience _one junior developer_, not **mine**. I'm not the junior developer. She expected this is covered by documentation. She didn't find out that. So I helped. She doesn't have/use Github so I reflect _different experience someone else_... I barely doubt she would have posted something to dry-rb forum.

So I decided to open this issue, since I feel this missing in the documentation too. I remember how I started I had a lot of problems with documentation various projects. I struggled on total basics and so on. And this kind of documentation make sure you're not wrong at all. So I feel empathic for her when she couldn't figure out how to use it in tests.

**Comment by timriley** [comment]
Hi folks, thanks for the discussion here. It'd certainly be nice to have some kind of beginner-friendly "how to test" guide for dry-rb gems in general, leaving any specific testing-related notes to reside within the documentation of each gem.

Like @waiting-for-dev points out, there's no special ceremony required for testing dry-monads objects, which is why such a page won't need to exist for that gem in particular.

Since there's no related issue in the dry-monads repo directly, I'll close this issue now. I do appreciate the feedback, @deepj, and we'll keep it in mind for when we can turn a greater amount of attention to expanding the documentation (and in the meantime, we are always happy to accept contributions from the community there too!).

Thanks ❤️

**Comment by bigsolom** [comment]
I came across this issue as I was also looking for some documentation for testing, for me it mainly boiled down to a couple of methods that I used in testing (I was mainly using `Result` monads in my code)

`success?` and `failure?` https://dry-rb.org/gems/dry-monads/1.3/result/#code-failure-code-and-code-success-code
-----------------------------------------------------------------------------------------------------------------------
`be_success` matched of rspec will call `.success?` method on the monad so it can be used to test whether the result was success or not
```ruby
expect(result).to be_success
expect(result).not_to be_success
expect(result.failure?).to be
```
`value!` https://dry-rb.org/gems/dry-monads/1.3/result/#code-value-code
--------------------------------------------------------------------------
To test the result in case of success
```ruby
expect(result.value!).to eq user
```

`failure` https://dry-rb.org/gems/dry-monads/1.3/result/#code-failure-code
----------------------------------------------------------------------------
To test the errors returned
```ruby
expect(result.failure).to eq(:not_found)
```

**Comment by masterT** [comment]
This is how I test it:

```ruby
it do
  is_expected.to be_success.and(
    have_attributes(
      success: repo.last
    )
  )
end
```

```ruby
it do
  is_expected.to be_failure.and(
    have_attributes(
      failure: :not_found
    )
  )
end
```

**Comment by flash-gordon** [comment]
How's it better than 
```ruby
include Dry::Monads[:result]

it { is_expected.to eql(Success(repo.last)) }

it { is_expected.to eql(Failure(:not_found)) }
```

**Comment by masterT** [comment]
Well, this is more clean. 👌

**Comment by masterT** [comment]
Note that my approach allows _RSpec_ matcher, which can be useful:

```ruby
it do
  is_expected.to be_success.and(
    have_attributes(
      success: be_a(Foo).and(
        have_attributes(
          bar: include(
            be_a(String)
          )
        )
      )
    )
  )
end
```

**Comment by arrowcircle** [comment]
Hey! I am trying to do something like

```ruby
allow_any_instance_of(MyClass).to receive(:result_method).and_return(Dry::Monads::Success(true))
```

But receive without any debug info:

```ruby
Module or String expected, got nil
```

How to properly solve this error?

**Comment by Andsbf** [comment]
@arrowcircle try `Dry::Monads::Success.new(true)`.  
"dot new" is the difference here

**Comment by 4ndv** [comment]
Another idea for cases when you need to check type of wrapped value without checking it's equality, using pattern matching in 2.7+ and rspec's `satisfy` matcher:

```ruby
it { is_expected.to(satisfy { |v| v in Success(OAuth2::AccessToken) }) }
it { is_expected.to(satisfy { |v| v in Failure[:exchange_code_error, OAuth2::Error] }) }
```

You know some premade matcher which can replace `satisfy` please let me know :)
